import enum
import uuid
from datetime import datetime

from sqlalchemy import BigInteger, CheckConstraint, ForeignKey, Index, Text, text
from sqlalchemy.dialects.postgresql import ARRAY, ENUM, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


def enum_values(enum_class: type[enum.Enum]) -> list[str]:
    """Persist enum values, not Python member names, to match the SQL schema."""
    return [member.value for member in enum_class]


class TenantStatus(str, enum.Enum):
    ACTIVE = "active"
    PAUSED = "paused"
    ARCHIVED = "archived"


class ScrapeJobStatus(str, enum.Enum):
    QUEUED = "queued"
    RUNNING = "running"
    SCRAPING = "scraping"
    DOWNLOADING = "downloading"
    CHUNKING = "chunking"
    EMBEDDING = "embedding"
    INDEXING = "indexing"
    READY = "ready"
    FAILED = "failed"
    CANCELED = "canceled"


class ApiKeyStatus(str, enum.Enum):
    ACTIVE = "active"
    REVOKED = "revoked"
    EXPIRED = "expired"


class DocumentType(str, enum.Enum):
    HTML = "html"
    PDF = "pdf"
    TEXT = "text"
    UNKNOWN = "unknown"


class Tenant(Base):
    """A single client website with isolated relational rows and vector payloads."""

    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    slug: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    root_url: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[TenantStatus] = mapped_column(
        ENUM(TenantStatus, name="tenant_status", values_callable=enum_values),
        nullable=False,
        server_default=TenantStatus.ACTIVE.value,
    )
    public_widget_key: Mapped[str] = mapped_column(
        Text, nullable=False, unique=True, server_default=text("encode(gen_random_bytes(16), 'hex')")
    )
    settings: Mapped[dict] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))
    archived_at: Mapped[datetime | None]

    scrape_jobs: Mapped[list["ScrapeJob"]] = relationship(back_populates="tenant")
    api_keys: Mapped[list["ApiKey"]] = relationship(back_populates="tenant")
    scraped_documents: Mapped[list["ScrapedDocument"]] = relationship(back_populates="tenant")


class ScrapeJob(Base):
    """Async ingestion status tracked for dashboard polling."""

    __tablename__ = "scrape_jobs"
    __table_args__ = (
        CheckConstraint("progress_current >= 0", name="ck_scrape_jobs_progress_current"),
        CheckConstraint("progress_total >= 0", name="ck_scrape_jobs_progress_total"),
        CheckConstraint("discovered_url_count >= 0", name="ck_scrape_jobs_discovered_url_count"),
        CheckConstraint("processed_document_count >= 0", name="ck_scrape_jobs_processed_document_count"),
        CheckConstraint("failed_url_count >= 0", name="ck_scrape_jobs_failed_url_count"),
        Index("idx_scrape_jobs_tenant_created", "tenant_id", "created_at"),
        Index("idx_scrape_jobs_status_created", "status", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    target_url: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[ScrapeJobStatus] = mapped_column(
        ENUM(ScrapeJobStatus, name="scrape_job_status", values_callable=enum_values),
        nullable=False,
        server_default=ScrapeJobStatus.QUEUED.value,
    )
    stage: Mapped[str] = mapped_column(Text, nullable=False, server_default="queued")
    progress_current: Mapped[int] = mapped_column(nullable=False, server_default="0")
    progress_total: Mapped[int] = mapped_column(nullable=False, server_default="0")
    discovered_url_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    processed_document_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    failed_url_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    error: Mapped[dict | None] = mapped_column(JSONB)
    requested_by: Mapped[str | None] = mapped_column(Text)
    started_at: Mapped[datetime | None]
    finished_at: Mapped[datetime | None]
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))

    tenant: Mapped[Tenant] = relationship(back_populates="scrape_jobs")


class ApiKey(Base):
    """Hashed tenant API credentials.

    Raw secrets should be generated by the API, displayed once, and discarded.
    """

    __tablename__ = "api_keys"
    __table_args__ = (Index("idx_api_keys_tenant_status", "tenant_id", "status"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    key_prefix: Mapped[str] = mapped_column(Text, nullable=False)
    key_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    scopes: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default=text("ARRAY['widget:chat']")
    )
    status: Mapped[ApiKeyStatus] = mapped_column(
        ENUM(ApiKeyStatus, name="api_key_status", values_callable=enum_values),
        nullable=False,
        server_default=ApiKeyStatus.ACTIVE.value,
    )
    last_used_at: Mapped[datetime | None]
    expires_at: Mapped[datetime | None]
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))
    revoked_at: Mapped[datetime | None]

    tenant: Mapped[Tenant] = relationship(back_populates="api_keys")


class ScrapedDocument(Base):
    """Canonical source document metadata used to audit and de-duplicate crawls."""

    __tablename__ = "scraped_documents"
    __table_args__ = (
        CheckConstraint("byte_size IS NULL OR byte_size >= 0", name="ck_scraped_documents_byte_size"),
        Index("idx_scraped_documents_tenant_type", "tenant_id", "doc_type"),
        Index("idx_scraped_documents_job", "scrape_job_id"),
        Index("uq_scraped_documents_tenant_canonical", "tenant_id", "canonical_url", unique=True),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    scrape_job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scrape_jobs.id", ondelete="SET NULL")
    )
    source_url: Mapped[str] = mapped_column(Text, nullable=False)
    canonical_url: Mapped[str] = mapped_column(Text, nullable=False)
    doc_type: Mapped[DocumentType] = mapped_column(
        ENUM(DocumentType, name="document_type", values_callable=enum_values),
        nullable=False,
        server_default=DocumentType.UNKNOWN.value,
    )
    title: Mapped[str | None] = mapped_column(Text)
    content_hash: Mapped[str | None] = mapped_column(Text)
    http_status: Mapped[int | None]
    byte_size: Mapped[int | None] = mapped_column(BigInteger)
    language: Mapped[str | None] = mapped_column(Text)
    metadata_: Mapped[dict] = mapped_column("metadata", JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    fetched_at: Mapped[datetime | None]
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=text("now()"))

    tenant: Mapped[Tenant] = relationship(back_populates="scraped_documents")
